name: Build & Test
on:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
      - run: ./gradlew check
